# Generated by Django 2.0.4 on 2018-05-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp_str',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='empty', max_length=50)),
                ('ad', models.CharField(default='empty', max_length=70)),
            ],
        ),
    ]
