# Generated by Django 2.0.4 on 2018-05-22 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_temp_str'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temp_str',
        ),
    ]
